name: Build Packer on Merge
on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build-packer:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Maven
        run: |
          pwd

      - name: Packer build
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: main.pkr.hcl
          working_directory: ami
        env:
          PACKER_LOG: 1 # enable debug log for packer
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
